baseURL = "https://do.shoogle.net/haiti-and-domrep/"
languageCode = "es"
title = "República Dominicana"
theme = "ln-base"

disableKinds = ["RSS", "robotsTXT"]
enableGitInfo = true

[outputs]
  home = ["HTML", "JSON"]
  section = ["HTML", "JSON"]

[params]
  site = "Shoogle"
  org = "lokal-ninja"
  repo = "haiti-and-domrep"

[taxonomies]
  shop = "shops"

